### ISSUE TITLE
Implement a command line transpilation tool

### ISSUE THREAD

**Issue by prashanthellina** [deep-compute/graphqls2s-transpiler#1]
The GraphQL specification defines a language called `GraphQL SDL` i.e Schema Definition Language that can be used to define the access layer for a web service.

However, this spec lacks some features like Type inheritance, Generics etc. Fortunately there is an open-source tool called `graphql-s2s` (https://github.com/nicolasdao/graphql-s2s) which defines a super-set of the GraphQL SDL language (let us call it `GraphQL-s2s SDL` for lack of a better name from the author). This tool provides a javascript library that has a `transpileSchema` method. When provided an input which is a GraphQL SDL based definition as a string, it converts/transpiles that to regular GraphQL SDL format (string output I believe).

What I miss is:

1. A simple command line tool that operates like this
    ```bash
    graphqls2s-transpiler input.s2s.graphql > output.regular.graphql # single file as input
    graphqls2s-transpiler input1.s2s.graphql input2.s2s.graphql > output.regular.graphql # two or more files as input but still single output to stdout
     ```
1. Ability to install this tool using `npm install graphqls2s-transpiler`

**Comment by prashanthellina** [comment]
@jaswanth098 This will help in making progress on deep-compute/gitalert#2.

**Comment by jaswanth098** [comment]
moving this ready-status with 1w duration

**Comment by prashanthellina** [comment]
@jaswanth098 Please attempt this on Friday this week. I'd love to have this available so I can continue work on `gitalert` when I am back in Canada.

**Comment by jaswanth098** [comment]
Sure

**Comment by jaswanth098** [comment]
This done and merged closing thia
