### ISSUE TITLE
Support multiple files as input to transpiler

### ISSUE THREAD

**Issue by ManishaBayya** [deep-compute/graphqls2s-transpiler#3]

**Comment by jaswanth098** [comment]
We need to support combining multiple schema files and generate destination schema

**Comment by ManishaBayya** [comment]
@jaswanth098 are you working on this or should we give this a try?

**Comment by UmangThapliyal** [comment]
@jaswanth098 Should I give PR for this?

**Comment by jaswanth098** [comment]
I have already supported this giving pr now

**Comment by UmangThapliyal** [comment]
> I have already supported this giving pr now

Saw now closed my PR

**Comment by jaswanth098** [comment]
This is done and merged closing this issue
